services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "9090:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
