services:
  backend:
    container_name: spotify-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - spotify-network

  frontend:
    container_name: spotify-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "9090:9090"
    networks:
      - spotify-network

networks:
  spotify-network:
    driver: bridge